controllers_user:
    resource:
        path: ../src/User/Infrastructure/InputAdapters/
        namespace: App\User\Infrastructure\InputAdapters
    type: attribute

api_user_rol_update:
  path: /api/user_rol_update
  controller: App\User\Infrastructure\InputAdapters\UpdateUserRoleController
  methods: [PUT]

controllers_client:
    resource:
        path: ../src/Client/Infrastructure/InputAdapters/
        namespace: App\Client\Infrastructure\InputAdapters
    type: attribute

controllers_product:
    resource:
        path: ../src/Product/Infrastructure/InputAdapters/
        namespace: App\Product\Infrastructure\InputAdapters
    type: attribute

controllers_ttn:
    resource:
        path: ../src/Ttn/Infrastructure/InputAdapters/
        namespace: App\Ttn\Infrastructure\InputAdapters
    type: attribute

controllers_scales:
    resource:
        path: ../src/Scales/Infrastructure/InputAdapters/
        namespace: App\Scales\Infrastructure\InputAdapters
    type: attribute
controllers_admin:
    resource:
        path: ../src/Admin/Infrastructure/InputAdapters/
        namespace: App\Admin\Infrastructure\InputAdapters
    type: attribute
controllers_weight_analytics:
    resource:
        path: ../src/WeightAnalytics/Infrastructure/InputAdapters/
        namespace: App\WeightAnalytics\Infrastructure\InputAdapters
    type: attribute

controller_subscription:
    resource:
        path: ../src/Subscription/Infrastructure/InputAdapters/
        namespace: App\Subscription\Infrastructure\InputAdapters
    type: attribute
controllers_infrastructure_services:
    resource:
        path: ../src/Infrastructure/Services/
        namespace: App\Infrastructure\Services
    type: attribute
controllers_stripe:
    resource:
        path: ../src/Stripe/Infrastructure/InputAdapters/
        namespace: App\Stripe\Infrastructure\InputAdapters
    type: attribute
controllers_alarm:
  resource:
    path: ../src/Alarm/Infrastructure/InputAdapters/
    namespace: App\Alarm\Infrastructure\InputAdapters
  type: attribute
controllers_dashboard:
  resource:
    path: ../src/Dashboard/Infrastructure/InputAdapters/
    namespace: App\Dashboard\Infrastructure\InputAdapters
  type: attribute
controllers_reports:
  resource:
    path: ../src/Report/Infrastructure/InputAdapters/
    namespace: App\Report\Infrastructure\InputAdapters
  type: attribute
controllers_ia:
  resource:
    path: ../src/IA/Infrastructure/InputAdapters/
    namespace: App\IA\Infrastructure\InputAdapters
  type: attribute
controllers_control_panel:
  resource:
    path: ../src/ControlPanel/
    namespace: App\ControlPanel
  type: attribute

